apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: ghcr.io/warps73/music-dl-front:1.0.0
          ports:
            - containerPort: 80
        - name: node-server
          image: ghcr.io/warps73/music-dl-api:1.0.0
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
